pipeline {
    agent {
        node {
            label 'agent'
        }
    }
    options {
        ansiColor('xterm')
    }

    stages {
        stage('Init') {
            steps {
                sh '''
                cd roboshop-infra-standard
                cd 01-vpc
                ls -ltr
                pwd
                terraform init
                '''
            }
        }
        stage('Plan') {
            steps {
                sh '''
                cd roboshop-infra-standard
                cd 01-vpc
                ls -ltr
                pwd
                terraform plan
                '''
            }
        }
    //     stage('Deploy') {
    //         steps {
    //             echo 'Deploying....'
    //         }
    //     }
    // }

    post {
        always {
            echo 'always'
        }
        success {
            echo 'i will run when success'
        }
        failure {
            echo 'i will run when failure'
        }
    }
}
